#!/usr/bin/env bash
# Regenerates ui/contracts.js from the Forge build (same compiler settings as the
# Etherscan-verified sources), so the MetaMask UI deploys exactly this repo's code.
set -euo pipefail
cd "$(dirname "$0")/.."
forge build >/dev/null
python3 - <<'EOF'
import json, hashlib
f = json.load(open("out/VestingFactory.sol/VestingFactory.json"))
t = json.load(open("out/TokenVesting.sol/TokenVesting.json"))
bytecode = f["bytecode"]["object"]
out = {
    "VestingFactory": {"abi": f["abi"], "bytecode": bytecode},
    "TokenVesting": {"abi": t["abi"]},
    "factoryBytecodeSha256": hashlib.sha256(bytes.fromhex(bytecode[2:])).hexdigest(),
}
with open("ui/contracts.js", "w") as fh:
    fh.write("// Generated by script/build-ui.sh from the Forge build. Do not edit.\n")
    fh.write("globalThis.CONTRACTS = " + json.dumps(out) + ";\n")
print("ui/contracts.js written, factory bytecode sha256", out["factoryBytecodeSha256"])
EOF
